i = 0;

% i = i+1; %1
% db(i).mouse_name    = 'M25';
% db(i).date          = '20180508';
% db(i).sessionType   = 5;
% db(i).session       = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
 
% i = i+1; %2
% db(i).mouse_name    = 'M25';
% db(i).date          = '20180509';
% db(i).sessionType   = 5;
% db(i).session       = 2;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %3
% db(i).mouse_name    = 'M25';
% db(i).date          = '';
% db(i).sessionType   = 5;
% db(i).session       = 3;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %4
% db(i).mouse_name    = 'M25';
% db(i).date          = '20180514';
% db(i).sessionType   = 5;
% db(i).session       = 4;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% i = i+1; %5
% db(i).mouse_name    = 'M25';
% db(i).date          = '20180515';
% db(i).sessionType   = 5;
% db(i).session       = 5;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
% 
% i = i+1; %6
% db(i).mouse_name    = 'M25';
% db(i).date          = '20180516';
% db(i).sessionType   = 5;
% db(i).session       = 6;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

% %% Single Sessions
% i = i+1; %1
% db(i).mouse_name    = 'M23';
% db(i).date          = '20180302';
% db(i).sessionType   = 5;
% db(i).session       = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;
% 
% i = i+1; %1
% db(i).mouse_name    = 'M24';
% db(i).date          = '20180302';
% db(i).sessionType   = 5;
% db(i).session       = 1;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 44; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;

%% Reference
i = i+1; %1
db(i).mouse_name    = 'M26';
db(i).date          = '20180508';
db(i).sessionType   = 5;
db(i).session       = 1;
db(i).diameter      = 8;
db(i).scanAmplitude = '1.8V';
db(i).nFrames       = 246;
db(i).samplingRate  = 14.5; %Hz
db(i).nTrials       = 60; %usable trials
db(i).comments      = 'TEC: 500 ms ISI';
db(i).trialDuration = 17; %in seconds
db(i).expts         = 1;
db(i).nplanes       = 1;
db(i).gchannel      = 1;
db(i).nplanes       = 1;
db(i).expred        = [];
db(i).nchannels_red = 0;

% i = i+1; %2
% db(i).mouse_name    = 'M26';
% db(i).date          = '20180509';
% db(i).sessionType   = 5;
% db(i).session       = 2;
% db(i).diameter      = 8;
% db(i).scanAmplitude = '1.8V';
% db(i).nFrames       = 246;
% db(i).samplingRate  = 14.5; %Hz
% db(i).nTrials       = 60; %usable trials
% db(i).comments      = 'TEC: 500 ms ISI';
% db(i).trialDuration = 17; %in seconds
% db(i).expts         = 1;
% db(i).nplanes       = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 0;