%"Dispatcher" by Kambadur Ananthamurthy
% This code uses actual dfbf curves from my data and analyses it for time
% cells using multiple methods
% Currently this is being tested for single session data. I will test with a
% batch, soon.

tic
clf
clear
close all

%% Addpaths
addpath(genpath('/Users/ananth/Documents/MATLAB/CustomFunctions')) % my custom functions
addpath(genpath('/Users/ananth/Documents/MATLAB/ImagingAnalysis')) % Additional functions
addpath(genpath('/Users/ananth/Documents/MATLAB/ImagingAnalysis/Suite2P-ananth'))
addpath('/Users/ananth/Documents/MATLAB/ImagingAnalysis/Suite2P-ananth/localCopies')

%% Dataset
make_db
ops0.fig                       = 1;
ops0.saveData                  = 1;
ops0.onlyProbeTrials           = 0;
ops0.loadSyntheticData         = 1;
ops0.doSigOnly                 = 0;

if ops0.loadSyntheticData
    setupSyntheticDataParameters
end

%% Figure details
if ops0.fig
    figureDetails = compileFigureDetails(20, 2, 10, 0.5, 'hot'); %(fontSize, lineWidth, markerSize, transparency, colorMap)
end

%% Main script
for iexp = 1:length(db)
    fprintf('Analyzing %s_%i_%i - Date: %s\n', db(iexp).mouseName, ...
        db(iexp).sessionType, ...
        db(iexp).session, ...
        db(iexp).date)
    saveDirec = '/Users/ananth/Desktop/Work/Analysis/Imaging/';
    saveFolder = [saveDirec db(iexp).mouseName '/' db(iexp).date '/'];
    
    %for i = 1:length(sdcp)
    %i = 1;
    i = length(sdcp);
    if ops0.loadSyntheticData
        load([saveFolder ...
            'synthDATA' ...
            '-' num2str(i) ...
            '_tCP' num2str(sdcp.timeCellPercent) ...
            '_cO' lower(sdcp.cellOrder) ...
            '_mHTP' num2str(sdcp.maxHitTrialPercent) ...
            '_hTPA' lower(sdcp.hitTrialPercentAssignment) ...
            '_tO' lower(sdcp.trialOrder) ...
            '_eW' num2str(sdcp.eventWidth{1}) ...
            '_eAF' sdcp.eventAmplificationFactor ...
            '_eT' lower(sdcp.eventTiming) ...
            '_sF' num2str(sdcp.startFrame) ...
            '_eF' num2str(sdcp.endFrame) ...
            '_iFWHM' num2str(sdcp.imprecisionFWHM) ...
            '_iT' lower(sdcp.imprecisionType) ...
            '_n' lower(sdcp.noise) ...
            '_np' num2str(sdcp.noisePercent) ...
            '.mat']);
        myData.dfbf = sdo.syntheticDATA;
        myData.dfbf_2D = sdo.syntheticDATA_2D;
        myData.baselines = zeros(size(sdo.syntheticDATA)); %initialization
    else
        %Load processed data (processed dfbf for dataset/session)
        myData = load([saveFolder db(iexp).mouseName '_' db(iexp).date '.mat']);
    end
    trialDetails = getTrialDetails(db(iexp));
    
    %Significant-Only Traces
    if ops0.doSigOnly
        if ops0.onlyProbeTrials
            disp('Only analysing Probe Trials ...')
            dfbf_sigOnly = findSigOnly(myData.dfbf(:, iProbeTrials, :));
        else
            dfbf_sigOnly = findSigOnly(myData.dfbf);
        end
        DATA = dfbf_sigOnly;
    else
        DATA = myData.dfbf;
    end
    
    %% Analysis Pipelines
    
    %Method A - Mehrab's Reliability Analysis (Bhalla Lab)
    pretr_control = 1;         %0 - analyses control no puff datasets, 1 - analyses training (trace or pseudo) datasets
    learned_only = 0;        %1 - use only datasets for animals that have learned the task 0 - use all datasets in list, 2 - analyses only non-learner datasets
    %Ca_width = 250;          %in ms
    stimOI = 1;              %stimulus of interest - 1 = tone, 2 = puff (useful with pseudorand datasets)
    %bk_period_control = 0;   %0 - analyses tone-puff period, 1 - analyses background period
    r_iters = 5000;           %number of iterations of randomisation used to find averaged r-shifted rb ratio - might have to go as high as 3000.
    non_ov_trials = 1;       %1 - non-overlapping trial sets used for kernel estimation and rb ratio calculation, 0 - all trials used for both
    early_only = 0;          %0 - uses all trials; 1 - uses only the first 5 trials of the session
    %ridge_h_width = 500; % in ms
    ridge_h_width = trialDetails.traceDuration;
    [mehrabOutput] = runMehrabR2BAnalysis(non_ov_trials, early_only, pk_behav_trial, ...
        dff_data_mat, CS_onset_frame, US_onset_frame, ridge_h_width, ...
        frame_time, r_iters);
    save([saveFolder db(iexp).mouseName '_' db(iexp).date '_mehrabAnalysis.mat' ], 'mehrabOutput')
    
    % ----
    
    %Method B - William Mau's Temporal Information (Eichenbaum Lab)
    [williamOutput] = runWilliamTIAnalysis(DATA);
    save([saveFolder db(iexp).mouseName '_' db(iexp).date '_williamAnalysis.mat' ], 'williamOutput')
    
    % ----
    
    %Method C - Simple Analysis
    delta = 3;
    skipFrames = [];
    [stcaOutput] = runSimpleTCAnalysis(DATA, delta, skipFrames);
    save([saveFolder db(iexp).mouseName '_' db(iexp).date '_simpleTCAnalysis.mat' ], 'stcaOutput')
    
    %% Second Order Stats to compare the outputs
    
    %Normalize the "reliability" vectors ignoring "Inf"
    sdo.Q_norm = (sdo.Q) ./max(sdo.Q);
    mehrabOutput.Q_norm = (mehrabOutput.Q) ./max(mehrabOutput.Q(~isinf(mehrabOutput.Q)));
    williamOutput.Q_norm = (williamOutput.Q) ./max(williamOutput.Q);
    stcaOutput.Q_norm = (stcaOutput.Q) ./max(stcaOutput.Q);
    
    %{
    %Combined save
    if ops0.saveData == 1
        save([saveFolder db(iexp).mouseName '_' db(iexp).date '_multipleAnalysisMethods.mat' ], ...
            'rrb_ratio_vec_final', 'timeCells_Mehrab', ...
            'Isec', 'timeCells_Eichenbaum')
    end
    %}
    %% Figures
    if ops0.fig == 1
        figure(1)
        clf
        plot(ones(length(mehrabOutput.Q)), 'k--')
        hold on
        plot(mehrabOutput.Q, 'g*')
        hold off
        title(['Mehrab | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | ' ...
            num2str(trialDetails.frameRate) ' Hz'], ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Cells', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        %set(gca,'YTick',[10, 20, 30, 40, 50, 60])
        %set(gca,'YTickLabel',({10; 20; 30; 40; 50; 60}))
        ylabel('Ridge/Background Ratio', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        if ops0.loadSyntheticData
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_mehrab_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session) '_synthData'],...
                '-djpeg');
        else
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_mehrab_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session)],...
                '-djpeg');
        end
        
        figure(2)
        clf
        plot(williamOutput.Q, 'b*')
        title(['William | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | '...
            num2str(trialDetails.frameRate) ' Hz | '...
            '3 frames/bin'] , ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Cells', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        %set(gca,'YTick',[10, 20, 30, 40, 50, 60])
        %set(gca,'YTickLabel',({10; 20; 30; 40; 50; 60}))
        ylabel('Temporal Information (bits/spike)', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        if ops0.loadSyntheticData
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_william_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session) '_synthData'],...
                '-djpeg');
        else
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_william_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session)],...
                '-djpeg');
        end
        
        figure(3)
        clf
        plot(stcaOutput.Q, 'b*')
        title(['Simple | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | '...
            num2str(trialDetails.frameRate) ' Hz | '...
            '3 frames/bin'] , ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Cells', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        %set(gca,'YTick',[10, 20, 30, 40, 50, 60])
        %set(gca,'YTickLabel',({10; 20; 30; 40; 50; 60}))
        ylabel('Hit Trial Ratio', ...
            'FontSize', figureDetails.fontSize,...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        if ops0.loadSyntheticData
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_simpleTC_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session) '_synthData'],...
                '-djpeg');
        else
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_simpleTC_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session)],...
                '-djpeg');
        end
        
        fig4 = figure(4);
        set(fig4,'Position',[300,300,1200,500])
        clf
        subplot(1,3,1)
        scatter(sdo.Q_norm, mehrabOutput.Q_norm);
        title(['Q vs R2B | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | ' ...
            num2str(trialDetails.frameRate) ' Hz'], ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Normalized Q', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        ylabel('Normalized R2B Ratio', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        subplot(1,3,2)
        scatter(sdo.Q_norm, williamOutput.Q_norm);
        title(['Q vs TI | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | ' ...
            num2str(trialDetails.frameRate) ' Hz'], ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Normalized Q', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        ylabel('Normalized TI', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        subplot(1,3,3)
        scatter(sdo.Q_norm, stcaOutput.Q_norm);
        title(['Q vs Hit Trials | ', ...
            db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | ' ...
            num2str(trialDetails.frameRate) ' Hz'], ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        xlabel('Normalized Q', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        ylabel('Normalized HT Ratio', ...
            'FontSize', figureDetails.fontSize, ...
            'FontWeight', 'bold')
        set(gca,'FontSize', figureDetails.fontSize-3)
        
        %         subplot(2,2,4)
        %         scatter(sdo.Q_norm, stcaOutput.Q_norm);
        %         title(['Q vs Hit Trials | ', ...
        %             db(iexp).mouseName ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ' | ' ...
        %             num2str(trialDetails.frameRate) ' Hz'], ...
        %             'FontSize', figureDetails.fontSize, ...
        %             'FontWeight', 'bold')
        %         xlabel('Temporal Information', ...
        %             'FontSize', figureDetails.fontSize, ...
        %             'FontWeight', 'bold')
        %         ylabel('Ridge/Background Ratio', ...
        %             'FontSize', figureDetails.fontSize, ...
        %             'FontWeight', 'bold')
        %         set(gca,'FontSize', figureDetails.fontSize-3)
        
        
        if ops0.loadSyntheticData
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_normScatter_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session) '_synthData'],...
                '-djpeg');
        else
            print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_normScatter_' ...
                db(iexp).mouseName '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session)],...
                '-djpeg');
        end
    end
end
toc