function jobData = harvestAnalyzedData(db, params)

if params.trim
    filename = sprintf('%s_%s_synthDataAnalysis_method%s_batch_%i-%i_run%i_trimmed.mat', ...
        db.mouseName, ...
        db.date, ...
        params.methodList, ...
        params.sdcpStart, ...
        params.sdcpEnd, ...
        params.trimRun);
else
        filename = sprintf('%s_%s_synthDataAnalysis_method%s_batch_%i-%i.mat', ...
        db.mouseName, ...
        db.date, ...
        params.methodList, ...
        params.sdcpStart, ...
        params.sdcpEnd);
end

direc = strcat(params.fileLocation, filename);

fprintf('Harvesting %s ...\n', filename)
jobData(params.sdcpStart:params.sdcpEnd) = load(direc);
disp(' ... done!')

end