%Plot 3 example cells
cells = [29 72 105];
%cells = [33 48 55];
fig11 = figure(11);
%Example time cells
%Rastors
set(fig11,'Position',[300,300,1200,300])
subplot(2,3,1)
imagesc(squeeze(cellRastor(cells(1),:,:)))
colormap(flipud(gray))
title([db(iexp).mouse_name ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ...
    ' | Cell '  num2str(cells(1))], ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('Trials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

subplot(2,3,2)
imagesc(squeeze(cellRastor(cells(2),:,:)))
colormap(flipud(gray))
title([db(iexp).mouse_name ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ...
    ' | Cell ' num2str(cells(2))], ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('Trials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

subplot(2,3,3)
imagesc(squeeze(cellRastor(cells(3),:,:)))
colormap(flipud(gray))
title([db(iexp).mouse_name ' ST' num2str(db(iexp).sessionType) ' S' num2str(db(iexp).session) ...
    ' | Cell ' num2str(cells(3))], ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('Trials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

%Frequency
subplot(2,3,4)
plot(cellFrequency(cells(1),:), 'black', 'LineWidth', figureDetails.lineWidth)
%ylim([0 size(cellRastor,2)])
ylim([0 50])
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('nTrials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

subplot(2,3,5)
plot(cellFrequency(cells(2),:), 'black', 'LineWidth', figureDetails.lineWidth)
%ylim([0 size(cellRastor,2)])
ylim([0 50])
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('nTrials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

subplot(2,3,6)
plot(cellFrequency(cells(3),:), 'black', 'LineWidth', figureDetails.lineWidth)
%ylim([0 size(cellRastor,2)])
ylim([0 50])
xticks([10 63 116 169 1222])
xticklabels({'-7314', '-3657', '0', '3657', '7314'})
xlabel('Time (ms)', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
ylabel('nTrials', ...
    'FontSize', figureDetails.fontSize, ...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)

print(['/Users/ananth/Desktop/figs/exampleTimeCells/threshold' num2str(threshold) '_' ...
    db(iexp).mouse_name '_' num2str(db(iexp).sessionType) '_' num2str(db(iexp).session)],...
    '-djpeg');