%     fig6 = figure(6);
%     set(fig6,'Position',[300, 300, 1000, 500])
%     clf
%     subplot(1, 3, 1)
%     imagesc(mEOutput.Yfit_actual_2D)
%     colormap('jet')
%     z = colorbar;
%     ylabel(z,'Frame Number', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     title('Ground Truth', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     xlabel('All Frames', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     ylabel('Trial Frame Number', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     set(gca,'FontSize', figureDetails.fontSize-3)
%     
%     subplot(1, 3, 2)
%     imagesc(mEOutput.Yfit_2D)
%     z = colorbar;
%     ylabel(z,'Frame Number', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     title('Prediction', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     xlabel('All Frames', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     ylabel('Trial Frame Number', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     set(gca,'FontSize', figureDetails.fontSize-3)
%     
%     subplot(1, 3, 3)
%     imagesc(mEOutput.YfitDiff_2D)
%     z = colorbar;
%     ylabel(z,'Difference in Frame Numbers', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     title('Error', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     xlabel('All Frames', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     ylabel('Trial Frame Number', ...
%         'FontSize', figureDetails.fontSize-2, ...
%         'FontWeight', 'bold')
%     
%     if ops0.loadSyntheticData
%         print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_methodE_' ...
%             db.mouseName '_' num2str(db.sessionType) '_' num2str(db.session) '_synthData'],...
%             '-djpeg');
%     else
%         print(['/Users/ananth/Desktop/figs/multipleTCA/multipleTCA_methodE_' ...
%             db.mouseName '_' num2str(db.sessionType) '_' num2str(db.session)],...
%             '-djpeg');
%     end