% %Make sure to run syntheticData_batch.m  before this.
% %% Q
% fig1 = figure(1);
% set(fig1, 'Position', [300, 300, 1000, 500])
% subplot(1, 2, 1)
% boxplot([sdo_batch(1).Q, sdo_batch(2).Q, sdo_batch(3).Q, sdo_batch(4).Q, sdo_batch(5).Q], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('Q vs Noise Percent - All Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Quality (Q)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% 
% subplot(1, 2, 2)
% boxplot([sdo_batch(1).Q(sdo_batch(1).ptcList), sdo_batch(2).Q(sdo_batch(2).ptcList), sdo_batch(3).Q(sdo_batch(3).ptcList), sdo_batch(4).Q(sdo_batch(4).ptcList), sdo_batch(5).Q(sdo_batch(5).ptcList)], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('Q vs Noise Percent - Putative Time Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Quality (Q)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QvsNoisePercent', '-dpng')
% 
% %Make sure to run multipleTimeCellAnalyses_batch.m  before this.
% % Method A - QA
% fig2 = figure(2);
% set(fig2, 'Position', [300, 300, 1000, 500])
% subplot(1, 2, 1)
% boxplot([mAOutput_batch(1).Q, mAOutput_batch(2).Q, mAOutput_batch(3).Q, mAOutput_batch(4).Q, mAOutput_batch(5).Q], ...
%     'Notch','on') %'Labels', {'0%', '25%', '50%', '75%', '100%'})
% %boxplot(mAOutput_batch(1).Q)
% title('QA vs Noise Percent - All Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method A - Quality (QA)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% 
% subplot(1, 2, 2)
% boxplot([mAOutput_batch(1).Q(mAOutput_batch(1).timeCells), mAOutput_batch(2).Q(mAOutput_batch(2).timeCells), mAOutput_batch(3).Q(mAOutput_batch(3).timeCells), mAOutput_batch(4).Q(mAOutput_batch(4).timeCells), mAOutput_batch(5).Q(mAOutput_batch(5).timeCells)], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QA vs Noise Percent - Putative Time Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method A - Quality (QA)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QAvsNoisePercent', '-dpng')
% 
% % Method B - QB
% fig3 = figure(3);
% set(fig3, 'Position', [300, 300, 1000, 500])
% subplot(1, 2, 1)
% boxplot([mBOutput_batch(1).Q, mBOutput_batch(2).Q, mBOutput_batch(3).Q, mBOutput_batch(4).Q, mBOutput_batch(5).Q], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QB vs Noise Percent - All Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method B - Quality (QB)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% 
% subplot(1, 2, 2)
% boxplot([mBOutput_batch(1).Q(mBOutput_batch(1).timeCells), mBOutput_batch(2).Q(mBOutput_batch(2).timeCells), mBOutput_batch(3).Q(mBOutput_batch(3).timeCells), mBOutput_batch(4).Q(mBOutput_batch(4).timeCells), mBOutput_batch(5).Q(mBOutput_batch(5).timeCells)], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QB vs Noise Percent - Putative Time Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method B - Quality (QB)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QBvsNoisePercent', '-dpng')
% 
% % Method C - QC1
% fig4 = figure(4);
% set(fig4, 'Position', [300, 300, 1000, 500])
% subplot(1, 2, 1)
% boxplot([mCOutput_batch(1).Q1,mCOutput_batch(2).Q1, mCOutput_batch(3).Q1, mCOutput_batch(4).Q1, mCOutput_batch(5).Q1], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QC1 vs Noise Percent - All Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method C - Quality (QC1)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% 
% subplot(1, 2, 2)
% boxplot([mCOutput_batch(1).Q1(mCOutput_batch(1).timeCells),mCOutput_batch(2).Q1(mCOutput_batch(2).timeCells), mCOutput_batch(3).Q1(mCOutput_batch(3).timeCells), mCOutput_batch(4).Q1(mCOutput_batch(4).timeCells), mCOutput_batch(5).Q1(mCOutput_batch(5).timeCells)], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QC1 vs Noise Percent - Putative Time Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method C - Quality (QC1)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QC1vsNoisePercent', '-dpng')
% 
% % Method C - QC2
% fig5 = figure(5);
% set(fig5, 'Position', [300, 300, 1000, 500])
% subplot(1, 2, 1)
% boxplot([mCOutput_batch(1).Q2,mCOutput_batch(2).Q2, mCOutput_batch(3).Q2, mCOutput_batch(4).Q2, mCOutput_batch(5).Q2], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QC1 vs Noise Percent - All Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method C - Quality (QC1)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% 
% subplot(1, 2, 2)
% boxplot([mCOutput_batch(1).Q2(mCOutput_batch(1).timeCells),mCOutput_batch(2).Q2(mCOutput_batch(2).timeCells), mCOutput_batch(3).Q2(mCOutput_batch(3).timeCells), mCOutput_batch(4).Q2(mCOutput_batch(4).timeCells), mCOutput_batch(5).Q2(mCOutput_batch(5).timeCells)], ...
%     'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
% title('QC1 vs Noise Percent - Putative Time Cells', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% ylabel('Method C - Quality (QC1)', ...
%     'FontSize', 16, ...
%     'FontWeight', 'bold')
% set(gca, 'FontSize', 15)
% print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QC2vsNoisePercent', '-dpng')

%Make sure to run syntheticData_batch.m  before this.
%% Q
fig1 = figure(1);
set(fig1, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([sdo_batch(1).Q, sdo_batch(2).Q, sdo_batch(3).Q, sdo_batch(4).Q, sdo_batch(5).Q], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('Q vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Quality (Q)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([sdo_batch(1).Q(sdo_batch(1).ptcList), sdo_batch(2).Q(sdo_batch(2).ptcList), sdo_batch(3).Q(sdo_batch(3).ptcList), sdo_batch(4).Q(sdo_batch(4).ptcList), sdo_batch(5).Q(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('Q vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Quality (Q)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QvsNoisePercent', '-dpng')

%Make sure to run multipleTimeCellAnalyses_batch.m  before this.
% Method A - QA
fig2 = figure(2);
set(fig2, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mAOutput_batch(1).Q, mAOutput_batch(2).Q, mAOutput_batch(3).Q, mAOutput_batch(4).Q, mAOutput_batch(5).Q], ...
    'Notch','on') %'Labels', {'0%', '25%', '50%', '75%', '100%'})
%boxplot(mAOutput_batch(1).Q)
title('QA vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method A - Quality (QA)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mAOutput_batch(1).Q(sdo_batch(1).ptcList), mAOutput_batch(2).Q(sdo_batch(2).ptcList), mAOutput_batch(3).Q(sdo_batch(3).ptcList), mAOutput_batch(4).Q(sdo_batch(4).ptcList), mAOutput_batch(5).Q(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QA vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method A - Quality (QA)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QAvsNoisePercent', '-dpng')

% Method B - QB
fig3 = figure(3);
set(fig3, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mBOutput_batch(1).Q, mBOutput_batch(2).Q, mBOutput_batch(3).Q, mBOutput_batch(4).Q, mBOutput_batch(5).Q], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QB vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method B - Quality (QB)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mBOutput_batch(1).Q(sdo_batch(1).ptcList), mBOutput_batch(2).Q(sdo_batch(2).ptcList), mBOutput_batch(3).Q(sdo_batch(3).ptcList), mBOutput_batch(4).Q(sdo_batch(4).ptcList), mBOutput_batch(5).Q(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QB vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method B - Quality (QB)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QBvsNoisePercent', '-dpng')

% Method C - QC1
fig4 = figure(4);
set(fig4, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mCOutput_batch(1).Q1,mCOutput_batch(2).Q1, mCOutput_batch(3).Q1, mCOutput_batch(4).Q1, mCOutput_batch(5).Q1], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mCOutput_batch(1).Q1(sdo_batch(1).ptcList), mCOutput_batch(2).Q1(sdo_batch(2).ptcList), mCOutput_batch(3).Q1(sdo_batch(3).ptcList), mCOutput_batch(4).Q1(sdo_batch(4).ptcList), mCOutput_batch(5).Q1(sdo_batch(4).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QC1vsNoisePercent', '-dpng')

% Method C - QC2
fig5 = figure(5);
set(fig5, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mCOutput_batch(1).Q2,mCOutput_batch(2).Q2, mCOutput_batch(3).Q2, mCOutput_batch(4).Q2, mCOutput_batch(5).Q2], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mCOutput_batch(1).Q2(sdo_batch(1).ptcList), mCOutput_batch(2).Q2(sdo_batch(2).ptcList), mCOutput_batch(3).Q2(sdo_batch(3).ptcList), mCOutput_batch(4).Q2(sdo_batch(4).ptcList), mCOutput_batch(5).Q2(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/QC2vsNoisePercent', '-dpng')

%% Normalized
fig1 = figure(1);
set(fig1, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([sdo_batch(1).normQ, sdo_batch(2).normQ, sdo_batch(3).normQ, sdo_batch(4).normQ, sdo_batch(5).normQ], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('normQ vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Norm Quality (normQ)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([sdo_batch(1).normQ(sdo_batch(1).ptcList), sdo_batch(2).normQ(sdo_batch(2).ptcList), sdo_batch(3).normQ(sdo_batch(3).ptcList), sdo_batch(4).normQ(sdo_batch(4).ptcList), sdo_batch(5).normQ(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('normQ vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Norm Quality (normQ)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/normQvsNoisePercent', '-dpng')

% Method A - normQA
fig2 = figure(2);
set(fig2, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mAOutput_batch(1).normQ, mAOutput_batch(2).Q, mAOutput_batch(3).Q, mAOutput_batch(4).Q, mAOutput_batch(5).Q], ...
    'Notch','on') %'Labels', {'0%', '25%', '50%', '75%', '100%'})
%boxplot(mAOutput_batch(1).Q)
title('normQA vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method A - Norm Quality (normQA)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mAOutput_batch(1).Q(sdo_batch(1).ptcList), mAOutput_batch(2).Q(sdo_batch(2).ptcList), mAOutput_batch(3).Q(sdo_batch(3).ptcList), mAOutput_batch(4).Q(sdo_batch(4).ptcList), mAOutput_batch(5).Q(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('normQA vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method A - Norm Quality (normQA)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/normQAvsNoisePercent', '-dpng')

% Method B - normQB
fig3 = figure(3);
set(fig3, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mBOutput_batch(1).normQ, mBOutput_batch(2).normQ, mBOutput_batch(3).normQ, mBOutput_batch(4).normQ, mBOutput_batch(5).normQ], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('normQB vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method B - Norm Quality (normQB)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mBOutput_batch(1).normQ(sdo_batch(1).ptcList), mBOutput_batch(2).normQ(sdo_batch(2).ptcList), mBOutput_batch(3).normQ(sdo_batch(3).ptcList), mBOutput_batch(4).normQ(sdo_batch(4).ptcList), mBOutput_batch(5).normQ(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('normQB vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method B - Norm Quality (normQB)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/normQBvsNoisePercent', '-dpng')

% Method C - normQC1
fig4 = figure(4);
set(fig4, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mCOutput_batch(1).normQ1,mCOutput_batch(2).normQ1, mCOutput_batch(3).normQ1, mCOutput_batch(4).normQ1, mCOutput_batch(5).normQ1], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mCOutput_batch(1).normQ1(sdo_batch(1).ptcList), mCOutput_batch(2).normQ1(sdo_batch(2).ptcList), mCOutput_batch(3).normQ1(sdo_batch(3).ptcList), mCOutput_batch(4).normQ1(sdo_batch(4).ptcList), mCOutput_batch(5).normQ1(sdo_batch(4).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/normQC1vsNoisePercent', '-dpng')

% Method C - QC2
fig5 = figure(5);
set(fig5, 'Position', [300, 300, 1000, 500])
subplot(1, 2, 1)
boxplot([mCOutput_batch(1).normQ2, mCOutput_batch(2).normQ2, mCOutput_batch(3).normQ2, mCOutput_batch(4).normQ2, mCOutput_batch(5).normQ2], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - All Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)

subplot(1, 2, 2)
boxplot([mCOutput_batch(1).normQ2(sdo_batch(1).ptcList), mCOutput_batch(2).normQ2(sdo_batch(2).ptcList), mCOutput_batch(3).normQ2(sdo_batch(3).ptcList), mCOutput_batch(4).normQ2(sdo_batch(4).ptcList), mCOutput_batch(5).normQ2(sdo_batch(5).ptcList)], ...
    'Notch','on','Labels', {'0%', '25%', '50%', '75%', '100%'})
title('QC1 vs Noise Percent - Putative Time Cells', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
ylabel('Method C - Quality (QC1)', ...
    'FontSize', 16, ...
    'FontWeight', 'bold')
set(gca, 'FontSize', 15)
print('/Users/Ananth/Desktop/figs/sensitivityAnalysis/normQC2vsNoisePercent', '-dpng')